site_name: AWS SA Professional
theme:
  name: material
  font:
    text: Helvetica
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

nav:
  - Accounts and Permissions:
    - AWS STS: permission-and-accounts/security-token-service.md
    - AWS Organizations: permission-and-accounts/aws-organizations.md
    - Policy Interpretation: permission-and-accounts/policy-interpretation.md
    - Permission Boundaries: permission-and-accounts/permission-boundaries.md
    - Permissions Evaluation : permission-and-accounts/permissions-evaluation.md
    - AWS Resource Access Manager: permission-and-accounts/resource-access-manager.md
    - Service Quotas: permission-and-accounts/service-quotas.md

  - Identities and Federation:
    - SAML 2.0: identities-and-federation/saml2.0.md
    - AWS SSO: identities-and-federation/sso.md
    - Amazon Cognito: identities-and-federation/amazon-cognito.md
    - Directory Service: identities-and-federation/directory-service.md
    - AWS Workspaces: identities-and-federation/workspaces.md

  - Networking and Hybrid:
    - Public vs Private Services: networking-and-hybrid/public-private-services.md
    - DHCP: networking-and-hybrid/dhcp.md
    - VPC Router: networking-and-hybrid/vpc-router.md
    - VPC Routing: networking-and-hybrid/vpc-routing.md
    - Stateful vs Stateless: networking-and-hybrid/stateless-vs-stateful.md
    - Border Gateway Protocol: networking-and-hybrid/border-gateway-protocol.md
    - Global Accelerator: networking-and-hybrid/global-accelerator.md
    - Transit Gateway: networking-and-hybrid/transit-gateway.md
    - IPSec VPN: networking-and-hybrid/ipsec-vpn.md
    - Site-to-Site VPN: networking-and-hybrid/site-to-site-vpn.md
    - Accelerated Site-to-Site VPN: networking-and-hybrid/site-to-site-accelerated.md 
    - AWS Client VPN: networking-and-hybrid/aws-client-vpn.md
    - Direct Connect: 
      - Direct Connect: networking-and-hybrid/direct-connect/direct-connect.md
    - Route 53: 
      - DNS: networking-and-hybrid/route53/dns.md
      - Fundamentals: networking-and-hybrid/route53/fundamentals.md
      - Hosted Zones: networking-and-hybrid/route53/hosted-zones.md
      - Routing Policies: networking-and-hybrid/route53/routing-policies.md
    - AWS PrivateLink: networking-and-hybrid/private-link.md
    - VPC Endpoints: networking-and-hybrid/vpc-endpoints.md
    - VPC DNS and DNS Endpoints: networking-and-hybrid/vpc-dns-endpoints.md
    - VPC IPv6: networking-and-hybrid/vpc-dns-endpoints.md
    - VPC Structure: networking-and-hybrid/vpc-structure.md
  - Storage Services:
    - File Systems: storage-services/file-system.md
    - S3:
      - Storage Classes: storage-services/s3/storage-classes.md
      - Lifecycle Configuration: storage-services/s3/lifecycle-configuration.md
      - Replication: storage-services/s3/replication.md
      - Object Encryption: storage-services/s3/encryption.md
      - Presigned URLs: storage-services/s3/presigned-urls.md
    - AWS Macie: storage-services/macie.md
    - EBS: storage-services/ebs.md
  - Compute & Load Balancing:
    - EC2: compute/ec2.md
    - ELB: compute/elb.md
    - ASG: compute/elb.md
    - Connection Draining: compute/connection-draining.md
  - Monitoring and Logging:
    - Cloudwatch: monitoring/cloudwatch.md
    - CloudTrail: monitoring/cloudtrail.md
    - AWS X-RAY: monitoring/x-ray.md
    - Cost Allocation Tags: monitoring/cost-allocation-tags.md
    - Trusted Advisor: monitoring/trusted-advisor.md
  - Databases:
    - RDS: databases/rds.md
    - Aurora: databases/aurora.md
    - DynamoDB: databases/dynamodb.md
    - ElasticSearch: databases/elasticsearch.md
    - Athena: databases/athena.md
    - Neptune: databases/neptune.md
    - Quantum Ledger: databases/quantum-ledger.md
  - Data Analytics:
    - Kinesis: data-analytics/kinesis.md
    - EMR: data-analytics/emr.md
    - RedShift: data-analytics/redshift.md
    - AWS Batch: data-analytics/aws-batch.md
    - AWS QuickSights: data-analytics/quicksight.md
  - Apps and Services:
    - ECS: app-services/ecs.md
    - SNS: app-services/sns.md
    - SQS: app-services/sqs.md
    - Amazon MQ: app-services/amazon-mq.md
    - Lambda: app-services/lambda.md
    - EventBridge: app-services/eventbridge.md
    - Simple Workflow Service: app-services/simple-workflow-service.md
    - AWS Mechanical Turk: app-services/mechanical-turk.md
    - Elastic Transcoder: app-services/media-convert.md
    - AWS IOT: app-services/iot.md
    - AWS Greengrass: app-services/greengrass.md

  - API Gateway: api-gateway/api-gateway.md
  - CloudFront: cloudfront/cloudfront.md

  - Serverless:
    - Step Functions: serverless/step-functions.md
    - AWS SAM: serverless/serverless-application-model.md
  - Deployment:
    - CICD: deployment/ci-cd.md
    - Elastic BeanStalk: deployment/elastic-beanstalk.md
    - AWS Opsworks: deployment/opsworks.md
    - AWS Service Catalog: deployment/service-catalog.md
    - AWS Systems Manager: deployment/systems-manager.md

  - Migration:
    - 6R migration: migration/migration.md
    - Database Migration: migration/migration-database.md
    - Virtual Machinne Migration: migration/migration-virtual-machines.md
    - Storage Gateway: migration/storage-gateway.md
    - AWS Snowball: migration/snowball.md
    - AWS Datasync: migration/datasync.md
    
  - Security & Configuration:
    - AWS Guard Duty: security-config/guardduty.md
    - AWS Config: security-config/config.md
    - AWS Inspector: security-config/inspector.md
    - Key Management Service: security-config/key-management-service.md
    - CloudHSM: security-config/cloud-hsm.md
    - AWS Certificate Manager: security-config/acm.md
    - AWS Parameter Store: security-config/parameter-store.md
    - AWS Secrets Manager: security-config/secrets-manager.md
    - VPC Flow Logs: security-config/vpc-flowlogs.md
    - AWS Shield & WAF: security-config/waf-shield.md

  - DR & BC:
    - DR Architecture: dr-bc/dr-bc-architecture.md
    - DR Storage: dr-bc/dr-storage.md
    - DR Compute: dr-bc/dr-compute.md
    - DR Database: dr-bc/dr-database.md
    - DR Networking: dr-bc/dr-networking.md
    
  - Miscellaneous:
    - AWS Lex & Connect: miscellaneous/lex-connect.md
    - AWS Rekognition: miscellaneous/rekognition.md
    - Kines Video Streams: miscellaneous/kinesis-video-streams.md
    - AWS Glue: miscellaneous/glue.md
    - AWS Device Farm: miscellaneous/device-farm.md


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
