site_name: AWS SA Professional
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

nav:
  - API Gateway: api-gateway/api-gateway.md
  - Migration:
    - 6R migration: migration/migration.md
  - Security & Configuration:
    - AWS Guard Duty: security-config/guardduty.md
    - AWS Config: security-config/config.md
    - AWS Inspector: security-config/inspector.md
    - Key Management Service: security-config/key-management-service.md
    - CloudHSM: security-config/cloud-hsm.md
    - AWS Certificate Manager: security-config/acm.md
    - AWS Parameter Store: security-config/parameter-store.md
    - AWS Secrets Manager: security-config/secrets-manager.md
    - VPC Flow Logs: security-config/vpc-flowlogs.md
    - AWS Shield & WAF: security-config/waf-shield.md
  - DR & BC:
    - DR Architecture: dr-bc/dr-bc-architecture.md
    - DR Storage: dr-bc/dr-storage.md
    - DR Compute: dr-bc/dr-compute.md
    - DR Database: dr-bc/dr-database.md
    - DR Networking: dr-bc/dr-networking.md
  - Miscellaneous:
    - AWS Lex & Connect: miscellaneous/lex-connect.md
    - AWS Rekognition: miscellaneous/rekognition.md
    - Kines Video Streams: miscellaneous/kinesis-video-streams.md
    - AWS Glue: miscellaneous/glue.md
    - AWS Device Farm: miscellaneous/device-farm.md